/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConselhosIndexRouteImport } from './routes/_authenticated/conselhos.index'
import { Route as AuthenticatedConferenciasIndexRouteImport } from './routes/_authenticated/conferencias.index'
import { Route as AuthenticatedConselhosNovoRouteImport } from './routes/_authenticated/conselhos.novo'
import { Route as AuthenticatedConferenciasNovaRouteImport } from './routes/_authenticated/conferencias.nova'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConselhosIndexRoute =
  AuthenticatedConselhosIndexRouteImport.update({
    id: '/conselhos/',
    path: '/conselhos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConferenciasIndexRoute =
  AuthenticatedConferenciasIndexRouteImport.update({
    id: '/conferencias/',
    path: '/conferencias/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConselhosNovoRoute =
  AuthenticatedConselhosNovoRouteImport.update({
    id: '/conselhos/novo',
    path: '/conselhos/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConferenciasNovaRoute =
  AuthenticatedConferenciasNovaRouteImport.update({
    id: '/conferencias/nova',
    path: '/conferencias/nova',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/conferencias/nova': typeof AuthenticatedConferenciasNovaRoute
  '/conselhos/novo': typeof AuthenticatedConselhosNovoRoute
  '/conferencias/': typeof AuthenticatedConferenciasIndexRoute
  '/conselhos/': typeof AuthenticatedConselhosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/conferencias/nova': typeof AuthenticatedConferenciasNovaRoute
  '/conselhos/novo': typeof AuthenticatedConselhosNovoRoute
  '/conferencias': typeof AuthenticatedConferenciasIndexRoute
  '/conselhos': typeof AuthenticatedConselhosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/conferencias/nova': typeof AuthenticatedConferenciasNovaRoute
  '/_authenticated/conselhos/novo': typeof AuthenticatedConselhosNovoRoute
  '/_authenticated/conferencias/': typeof AuthenticatedConferenciasIndexRoute
  '/_authenticated/conselhos/': typeof AuthenticatedConselhosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/conferencias/nova'
    | '/conselhos/novo'
    | '/conferencias/'
    | '/conselhos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/conferencias/nova'
    | '/conselhos/novo'
    | '/conferencias'
    | '/conselhos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/conferencias/nova'
    | '/_authenticated/conselhos/novo'
    | '/_authenticated/conferencias/'
    | '/_authenticated/conselhos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conselhos/': {
      id: '/_authenticated/conselhos/'
      path: '/conselhos'
      fullPath: '/conselhos/'
      preLoaderRoute: typeof AuthenticatedConselhosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conferencias/': {
      id: '/_authenticated/conferencias/'
      path: '/conferencias'
      fullPath: '/conferencias/'
      preLoaderRoute: typeof AuthenticatedConferenciasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conselhos/novo': {
      id: '/_authenticated/conselhos/novo'
      path: '/conselhos/novo'
      fullPath: '/conselhos/novo'
      preLoaderRoute: typeof AuthenticatedConselhosNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conferencias/nova': {
      id: '/_authenticated/conferencias/nova'
      path: '/conferencias/nova'
      fullPath: '/conferencias/nova'
      preLoaderRoute: typeof AuthenticatedConferenciasNovaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedConferenciasNovaRoute: typeof AuthenticatedConferenciasNovaRoute
  AuthenticatedConselhosNovoRoute: typeof AuthenticatedConselhosNovoRoute
  AuthenticatedConferenciasIndexRoute: typeof AuthenticatedConferenciasIndexRoute
  AuthenticatedConselhosIndexRoute: typeof AuthenticatedConselhosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedConferenciasNovaRoute: AuthenticatedConferenciasNovaRoute,
  AuthenticatedConselhosNovoRoute: AuthenticatedConselhosNovoRoute,
  AuthenticatedConferenciasIndexRoute: AuthenticatedConferenciasIndexRoute,
  AuthenticatedConselhosIndexRoute: AuthenticatedConselhosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
